### ISSUE TITLE
[help wanted] i want to enable/disable screenshot

### ISSUE THREAD

**Issue by AMBE1203** [kuttz/SecureYourView#1]
Thanks for your example project.
but i want to have the following functionality, there are two buttons, clicking the first button will block screen recording, and clicking the second button will enable screen recording.
Help me please!

**Comment by kuttz** [comment]
Yes. You can do that. I am attaching the sample code below. Anything in the **YourSecureView** will be secure also you can toggle the secure property of that view using the **isSecure** value.

```
class YourSecureView: UIView {
    
    fileprivate let secureField = UITextField()
    
    var isSecure: Bool = true {
        didSet {
            secureField.isSecureTextEntry = isSecure
        }
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        commenInit()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        commenInit()
    }
    
    fileprivate func commenInit() {
        
        secureField.isSecureTextEntry = true
        self.addSubview(secureField)
        secureField.centerYAnchor.constraint(equalTo: self.centerYAnchor).isActive = true
        secureField.centerXAnchor.constraint(equalTo: self.centerXAnchor).isActive = true
        self.layer.superlayer?.addSublayer(secureField.layer)
        secureField.layer.sublayers?.first?.addSublayer(self.layer)
    }
    
}
```

**Comment by AMBE1203** [comment]
I'm flutter and kotlin/android developer, so i don't know swift very well, can you create a project sample for me.
Thank you!.

**Comment by kuttz** [comment]
I'm not femilier with flutter either.

**Comment by AMBE1203** [comment]
can you help me create a project sample with swift or object-C and i will use it to module in my project flutter

**Comment by kuttz** [comment]
Sure, I will create a branch for you.

**Comment by Luismi74** [comment]
I am also a flutter developer and looking into having this working on Flutter with Swift configuration. 

To give you some context @kuttz, here is how our appDelegate.swift looks:
```dart
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by kuttz** [comment]
@AMBE1203 check the new [branch](https://github.com/kuttz/SecureYourView/tree/enabledisable-screenshot) attached to this issue.

**Comment by AMBE1203** [comment]
it works fine, thank you very much
